# Generated by Django 5.2 on 2025-05-05 01:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rede_social', '0003_alter_friendship_unique_together_friendship_friend_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendship',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
